### ISSUE TITLE
 `~/.cargo/bin` needs to be added to the path on systems that call the bash profile `~/.bash_profile`

### ISSUE THREAD

**Issue by rachlmac** [hawkw/sos-kernel#53] opened 2016-11-07 19:13 UTC

**Comment by hawkw** [comment] 2016-11-07 19:21
This is a little bit more complex than #52, but not significantly. Basically, after we install `cargo` (`install-env.sh`, on [line 60](https://github.com/hawkw/sos-kernel/blob/master/scripts/install-env.sh#L60), we need to check for the existence of a `~/.bash_profile` file and if it exists, we add a line  saying `export PATH=$PATH:$HOME/.cargo/bin` to it.

**Comment by hawkw** [comment] 2016-11-07 19:23
Maybe the real Best Practices Solution to this would be to open an issue on [rust-lang-nursery/rustup.rs](https://github.com/rust-lang-nursery/rustup.rs), but they might already be aware of this issue/it might be working as intended for some kind of reason.

**Comment by hawkw** [comment] 2016-11-07 19:24
@rachlmac, would you like to be in charge of fixing this one, too? it shouldn't be too bad, but if you need help, let me know.

**Comment by rachlmac** [comment] 2016-11-07 19:30
@hawkw Yes, I will go ahead and look into this and keep you updated if I run into any road blocks. Thanks!

**Comment by hawkw** [comment] 2016-11-07 19:33
Awesome, thanks!

**Comment by hawkw** [comment] 2018-01-21 04:34
I believe this was fixed in #61

**Closed as completed by hawkw** 2018-01-21 04:34 UTC
Labels: contrib/easy, area/build, contrib/good first issue
